## What is Numpy ?
  
NumPy is a library for the Python programming language, **adding support for large, multi-dimensional arrays and matrices**, along with a large collection of **high-level mathematical functions to operate on these arrays.**

* A matrix is a two-dimensional data structure where numbers are arranged into rows and columns. 
* In Numpy dimensions are called axes. The number of axes is rank.
* The first axis ( i.e. axis-0 ) is running vertically downwards across rows, and the second (axis-1) running horizontally across columns.

## Importing  required libraries

In [224]:
import numpy as np
print('numpy version : ', np.__version__)

numpy version :  1.24.4


## 1.np.array()

In [225]:
digits = np.array([
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
])

print('type(digits) : ', type(digits))
digits

type(digits) :  <class 'numpy.ndarray'>


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 2.shape and reshape()

In [226]:
temperatures = np.array([
    29.3, 42.1, 18.8, 16.1, 38.0, 12.5,
    12.6, 49.9, 38.6, 31.3, 9.2, 22.2
]).reshape(3,4)

print('temperatures shape() : ', temperatures.shape)
temperatures

temperatures shape() :  (3, 4)


array([[29.3, 42.1, 18.8, 16.1],
       [38. , 12.5, 12.6, 49.9],
       [38.6, 31.3,  9.2, 22.2]])

## 3.shape and reshape() with arange()

In [227]:
mat1 = np.arange(6).reshape((3, 2))

print('mat1 shape : ', mat1.shape)
mat1

mat1 shape :  (3, 2)


array([[0, 1],
       [2, 3],
       [4, 5]])

In [228]:
mat2 = np.arange(24).reshape((2, 3, 4))
mat2

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [229]:
mat3 = np.arange(24).reshape((4, 3, 2))
mat3

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

## 4.swapaxes()

In [230]:
mat4 = np.arange(6).reshape((3, 2))

print('mat4 shape : ', mat4.shape)
mat4

mat4 shape :  (3, 2)


array([[0, 1],
       [2, 3],
       [4, 5]])

In [231]:
mat5 = np.swapaxes(mat4, 0, 1)

print('mat5 shape : ', mat5.shape)
mat5

mat5 shape :  (2, 3)


array([[0, 2, 4],
       [1, 3, 5]])

## 5.Understanding Axes

In [232]:
table = np.array([
    [5, 3, 7, 1],
    [2, 6, 7 ,9],
    [1, 1, 1, 1],
    [4, 3, 2, 0],
])

print('table.max() : ', table.max())
print('table.max(axis=0) : ', table.max(axis=0))
print('table.max(axis=1) : ', table.max(axis=1))

table.max() :  9
table.max(axis=0) :  [5 6 7 9]
table.max(axis=1) :  [7 9 1 4]


## 6.Matrix Operations

In [233]:
X = np.array([[1, 2], [4, 5]]) 
X

array([[1, 2],
       [4, 5]])

In [234]:
Y = np.array([[7, 8], [9, 10]])
Y

array([[ 7,  8],
       [ 9, 10]])

### 6.1.Addition

In [235]:
print('Add : ', np.add(X, Y))

Add :  [[ 8 10]
 [13 15]]


### 6.2.Substraction

In [236]:
print('Sub : ', np.subtract(X, Y))

Sub :  [[-6 -6]
 [-5 -5]]


### 6.3.Division

In [237]:
print('Div : ', np.divide(X, Y))

Div :  [[0.14285714 0.25      ]
 [0.44444444 0.5       ]]


### 6.4.Element wise Multiplication

In [238]:
print('Element wise Multiplication : ', np.multiply(X, Y))

Element wise Multiplication :  [[ 7 16]
 [36 50]]


### 6.5.Dot of Matrix

In [239]:
print('Dot of Matrix : ', np.dot(X, Y))

Dot of Matrix :  [[25 28]
 [73 82]]


## 7.Slicing - Two-dimensional Numpy Arrays

In [240]:
square = np.array([
    [16, 3, 2, 13],
    [5, 10, 11, 8],
    [9, 6, 7, 12],
    [4, 15, 14, 1]
])

square

array([[16,  3,  2, 13],
       [ 5, 10, 11,  8],
       [ 9,  6,  7, 12],
       [ 4, 15, 14,  1]])

In [241]:
print('square[0][0] : ', square[0][0])
print('square[0][0] : ', square[1][2])
print('square[-][-1] : ', square[-1][-1])

square[0][0] :  16
square[0][0] :  11
square[-][-1] :  1


## 8.Slice a Range of Values from Two-dimensional Numpy Arrays

In [242]:
square

array([[16,  3,  2, 13],
       [ 5, 10, 11,  8],
       [ 9,  6,  7, 12],
       [ 4, 15, 14,  1]])

In [243]:
print(square[0:1, 0:2])

[[16  3]]


In [244]:
print(square[0:3, 0:2])

[[16  3]
 [ 5 10]
 [ 9  6]]


In [245]:
print(square[:3, 1:])

[[ 3  2 13]
 [10 11  8]
 [ 6  7 12]]


In [246]:
print(square[:3, 1:].sum())

72


In [247]:
print(square[:, 1])

[ 3 10  6 15]


## 9.Masking and Filtering

In [248]:
numbers = np.linspace(5, 50, 24, dtype=int).reshape(4, -1)
numbers

array([[ 5,  6,  8, 10, 12, 14],
       [16, 18, 20, 22, 24, 26],
       [28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50]])

In [249]:
mask = numbers % 4 == 0
mask

array([[False, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False]])

In [250]:
numbers[mask]

array([ 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48])

## 10.Transposing

In [251]:
a = np.array([
    [1, 2],
    [3, 4],
    [5, 6],
])

a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [252]:
print('a.T :', a.T)

a.T : [[1 3 5]
 [2 4 6]]


In [253]:
print('a.transpose() :', a.transpose())

a.transpose() : [[1 3 5]
 [2 4 6]]


## 11.Sorting

In [254]:
data = np.array([
    [7, 1, 4],
    [8, 6, 5],
    [1, 2, 3]
])

In [255]:
print(np.sort(data))

[[1 4 7]
 [5 6 8]
 [1 2 3]]


In [256]:
data

array([[7, 1, 4],
       [8, 6, 5],
       [1, 2, 3]])

In [257]:
print('np.sort(data, axis=None) : ', np.sort(data, axis=None))

np.sort(data, axis=None) :  [1 1 2 3 4 5 6 7 8]


In [258]:
print('np.sort(data, axis=0) : ', np.sort(data, axis=0))

np.sort(data, axis=0) :  [[1 1 3]
 [7 2 4]
 [8 6 5]]


In [259]:
print('np.sort(data, axis=1) : ', np.sort(data, axis=1))

np.sort(data, axis=1) :  [[1 4 7]
 [5 6 8]
 [1 2 3]]


## 12.Concatenation

In [260]:
a = np.array([
    [4, 8],
    [6, 1]
])

b = np.array([
    [3, 5],
    [7, 2],
])

In [261]:
print('np.hstack((a, b)) : ', np.hstack((a, b)))

np.hstack((a, b)) :  [[4 8 3 5]
 [6 1 7 2]]


In [262]:
print('np.vstack((b, a)) : ', np.vstack((b, a)))

np.vstack((b, a)) :  [[3 5]
 [7 2]
 [4 8]
 [6 1]]


In [263]:
print('np.concatenate((b, a)) : ', np.concatenate((b, a)))

np.concatenate((b, a)) :  [[3 5]
 [7 2]
 [4 8]
 [6 1]]


In [264]:
print('np.concatenate((b, a), axis=None)' , np.concatenate((b, a), axis=None))

np.concatenate((b, a), axis=None) [3 5 7 2 4 8 6 1]


In [265]:
print('np.concatenate((b, a), axis=0)' , np.concatenate((b, a), axis=0))

np.concatenate((b, a), axis=0) [[3 5]
 [7 2]
 [4 8]
 [6 1]]


In [266]:
print('np.concatenate((b, a), axis=1)' , np.concatenate((b, a), axis=1))

np.concatenate((b, a), axis=1) [[3 5 4 8]
 [7 2 6 1]]


## 13.np.ones()

In [267]:
ones_1 = np.ones((1, 3, 4), dtype=np.int16)
ones_1

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [268]:
ones_2 = np.ones((2, 5, 5), dtype=np.int16)
ones_2

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=int16)

## 14.np.zeros()

In [269]:
zeros_1 = np.zeros((1, 3, 4), dtype=np.int16)
zeros_1

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int16)

In [270]:
zeros_2 = np.zeros((2, 5, 5), dtype=np.int16)
zeros_2

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]], dtype=int16)

## Quick Recap

* **np.array():** is used to create numpy array from multidimensional array.
* **type():** is used to tell the object class.
* **reshape():** is used to reshape a matrix.
* **arange():** is one of the array creation routines based on numerical ranges.
* **reshape():** can be used for 2-D and 3-D matrix, by mentioning reshape(rows, column) reshape(depth, rows, column) respectively.
* **swapaxes():** is used to interchange only two axis.
* **matrix.max():** is used for find the max value  from matrix.
* **matrix.max(axis=0):** is used for find the max value on axis=0 of matrix.
* **matrix.max(axis=1):** is used for find the max value on axis=1 of matrix.
* **np.add():** is used for addition of two matrix.
* **np.subtract():** is used for subtraction of two matrix.
* **np.divide():** is used for division of two matrix.
* **np.multiply():** is used for element wise multiplication of two matrix.
* **np.dot():** is used for dot product of two matrix.
* **matrix[row_index][column_index]:** is used to perform indexing on matrix. 
    * Indexing range and all remain same as python indexing, which start with 0 and end on stop-1.
    * Slice a Range of Values from Two-dimensional Numpy Arrays
        * Synatx : **matrix[rows-range , columns-range]**
        * Example : **matrix[0:1, 0:2]**
* **np.linspace()** generates n numbers evenly distributed between a minimum and a maximum, which is useful for evenly distributed sampling in scientific plotting.
* **matrix.T:** is used for transpose.
* **a.transpose():** is used for transpose.
* **np.sort():** is used to short the matrix, it can also sort based on axis basic by-default shorting is row based sorting.
* **np.hstack():** is used to used to stack two matrix horizontal.
* **np.vstack():** is used to used to stack two matrix vertically.
* **np.concatenate():** is used to concatenate  two matrix vertically and also along with axis.
* Statistical Functions including **.min(), .max(), .mean(), .median() and .std().**
* **.sum():** is used for aggregate.
* **np.zeros(depth, rows, columns) and np.ones(depth, rows, columns)**  used to creates a matrix full of zeros or ones.
* **np.logspace()** returns even spaced numbers on a log scale. Logspace has the same parameters as **np.linspace().**